<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Exceptions\Exceptions.csproj" />
    <ProjectReference Include="..\Model\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Login\" />
    <Folder Include="UseCases\Profile\" />
    <Folder Include="UseCases\Update\" />
    <Folder Include="UseCases\TrocarSenha\" />
  </ItemGroup>

</Project>
